version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-net
    depends_on:
      - db-vehicle
    ports:
      - "9003:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    command: >
      sh -c "
      chown -R www-data:www-data storage bootstrap/cache &&
      chmod -R 775 storage bootstrap/cache &&
      php-fpm
      "

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-vehicle
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # ✅ ini benar!
    depends_on:
      - app
    networks:
      - laravel-net
  
  hasura-vehicle:
    image: hasura/graphql-engine:v2.34.0
    ports:
      - "8086:8080"  # GUNAKAN PORT BERBEDA AGAR TIDAK BENTROK
    restart: always
    depends_on:
      - db-vehicle
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:admin123@db-vehicle:5432/motor_wash_vehicle_service
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret-vehicle
    networks:
      - laravel-net

  db-vehicle:
    image: postgres:17
    container_name: db-vehicle
    restart: unless-stopped
    environment:
      POSTGRES_DB: motor_wash_vehicle_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-net
    ports:
      - "5435:5432"
    

volumes:
  pgdata:


networks:
  laravel-net:
    external: true


